FROM php:7.4

# tell the port number the container should expose
EXPOSE 80

COPY . .

RUN apt-get update && apt-get install -y wget

RUN docker-php-ext-configure pdo_mysql
RUN docker-php-ext-install pdo_mysql

# run the command
CMD ["php", "-S", "0.0.0.0:80", "-t", "./"]
